name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
    - name: Delete previous artifact
      uses: geekyeggo/delete-artifact@v2
      with:
        name: android-debug-apk
      continue-on-error: true
    - name: Build debug APK
      run: ./gradlew clean :android:assembleDebug
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-debug-apk
        path: android/build/outputs/apk/debug/*.apk
